config/routes.rb
Rails.application.routes.draw do
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts, only: [:index, :new, :create]
  devise_for :users
  get 'users/show'
  root 'posts#index'
  
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  # Callback
  after_commit :broadcast_request, on: :create
  
  # Associations
  belongs_to :user
  
  # Associations validations
  validates :user, presence: true
  
  # Fields validations
  validates :title, presence: true
  
  def broadcast_request
    if self.is_private
      self.user.friends.each do |friend|
        ActionCable.server.broadcast "private_post_channel_#{friend.id}", title: self.title
      end
    else
      ActionCable.server.broadcast 'post_channel', title: self.title
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable
         
  # Associations
  has_many :friendships
  has_many :posts, dependent: :destroy
  has_many :received_friendships, class_name: "Friendship", foreign_key: "friend_id"
  
  has_many :active_friends, -> { where(friendships: { accepted: true}) }, through: :friendships, source: :friend
  has_many :received_friends, -> { where(friendships: { accepted: true}) }, through: :received_friendships, source: :user
  has_many :pending_friends, -> { where(friendships: { accepted: false}) }, through: :friendships, source: :friend
  has_many :requested_friendships, -> { where(friendships: { accepted: false}) }, through: :received_friendships, source: :user
  
  # Fields validations
  validates_format_of :email, with: Devise::email_regexp
  validates :password, presence: true
  
  def friends
    active_friends | received_friends
  end
  
  def pending
      pending_friends | requested_friendships
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      flash[:notice] = 'Friend requested.'
      redirect_back(fallback_location: users_show_path)
    else
      flash[:error] = 'Unable to request friendship.'
      redirect_back(fallback_location: users_show_path)
    end
  end
  
  def update
    @friendship = Friendship.find_by(user_id: params[:id])
    @friendship.update(accepted: true)
    if @friendship.save
      redirect_to root_url, notice: 'Successfully confirmed friend!'
    else
      redirect_to root_url, notice: 'Sorry! Could not confirm friend!'
    end
  end
  
  def destroy
    @friendship = Friendship.find_by(user_id: params[:id])
    @friendship.destroy
    flash[:notice] = 'Removed friendship.'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    posts_id = []
    Post.all.each do |post|
      if post.is_private && (post.user.friends.include?(current_user) || post.user == current_user)
        posts_id << post.id
      elsif !post.is_private
        posts_id << post.id
      end
    end
    
    @posts = Post.where(id: posts_id.flatten).paginate(page: params[:page], per_page: 5).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end
  
  private
    def post_params
      params.require(:post).permit(:is_private, :title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user_friends = current_user.friends
    @user_pending = current_user.pending
    
    ids = @user_friends.pluck(:id) +  @user_pending.pluck(:id) + current_user.id.to_s.split('')
    @users = User.where.not(id: ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/friendships/update.html.erb
<h1>Friendships#update</h1>
<p>Find me in app/views/friendships/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-bar">
      <ul class="nav-bar-el">
        <% if user_signed_in? %>
          <li class="user-name"><%= current_user.email %></li>
          <li class="link-contaner"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <li class="link-contaner"><%= link_to 'Post', posts_path %></li>
          <li class="link-contaner"><%= link_to 'User info', users_show_path %></li>
        <% else %>
          <li class="link-contaner">
            <%= link_to('Login', new_user_session_path)  %>
            <li class="link-contaner"><%= link_to 'Post', posts_path %></li>
          </li>
        <% end %>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="main-container">
  <div class="new-post">
    <%= link_to 'New Post', new_post_path %>
  </div>
  <ul id="post">
    <% @posts.each do |post| %>
        <li><%= post.title %></li>
    <% end %>
  </ul>
  <div class="flickr_pagination">
    <%= will_paginate @posts%>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-center">
  <div class="post-form">
    <h3 class="text-left">Create new post</h1>

    <%= form_for @post do |f| %>
      <% if @post.errors.any? %>
      <% end %>
      
      <div class="field">
        <%= f.label :title, class: "text" %>
        <%= f.text_field :title, class: "post-text-field"%>
      </div>
      
      <div class="field">
        <%= f.label :is_private, class: "text" %>
        <%= f.check_box :is_private%>
      </div>
      
      <div class="action">
        <%= f.submit "Post", class: "button" %>
      </div>
    <% end %>
   </div>
 </div>

app/views/users/show.html.erb
<div class="flash">
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% elsif flash[:error]%>
    <div class="error"><%= flash[:error] %></div>
  <% end %>
</div>
<div class="main-container">
  <% if current_user.requested_friendships.count > 0 %>
    <table id="requests">
      <h3>Requests</h3>
      <% current_user.requested_friendships.each do |request| %>
        <tr>
          <td><%= request.email %></td>
          <td class="el-right">
            <%= link_to "Accept",  friendship_path(id: request.id), method: "put" %>
            <%= link_to "Decline", friendship_path(id: request.id), method: :delete %>
          </td>
        </tr>
      <% end %>
      </td>
    </table>
  <% end %>

  <table id="not-friends">
    <h3>Users you can know</h3>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td class="el-right"><%= link_to "Add Friend", friendships_path(friend_id: user), method: :post %></td>
    </tr>
    <% end %>
  </table>

  <table id="friends">
    <h3>Friends</h3>
    <% @user_friends.each do |friend| %>
    <tr>
      <td><%= friend.email %></td>
    </tr>
    <% end %>
  </table>
</div>